thread 'main' panicked at src/main.rs:404:10:
called `Result::unwrap()` on an `Err` value: IllegalState("Could not spawn the forkserver: Os {\n    code: 13,\n    kind: PermissionDenied,\n    message: \"Permission denied\",\n}", ErrorBacktrace)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
